---
 - name: installing additional packages
   yum: name={{ item }} state=latest
   with_items:
      - "{{ yum_install_packages }}"

 - name: remove unnecessary packages
   yum: name={{ item }} state=absent
   with_items:
      - "{{ yum_remove_packages }}"

 - name: yum update all packages
   yum: name=* state=latest

 - name: disable SELinux
   selinux: state=disabled

 - name: enable services
   systemd: name={{ item }} state=started enabled=yes 
   with_items:
      - "{{ enabled_services }}"
   when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

# - name: disable services
#   systemd: name={{ item }} state=stopped 
#   with_items:
#      - "{{ disabled_services }}"
#   when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

# - name: Rebooting server
#   command: /sbin/shutdown -r +1
#   async: 0
#   poll: 0
